version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: habit_tracker_postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: habit_tracker_bot
    depends_on:
      - db
    environment:
      - TELEGRAM_BOT_TOKEN=7077048864:AAEXg1Pd1JBuMClBY5zO3lIMJirRjJ0qA_0
      #- TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
volumes:
  db_data: